package com.example.geogenius.model

import com.example.geogenius.R

val countries = mapOf(
    "Afghanistan" to R.drawable.af,
    "Aland Islands" to R.drawable.ax,
    "Albania" to R.drawable.al,
    "Algeria" to R.drawable.dz,
    "American Samoa" to R.drawable.`as`,
    "Andorra" to R.drawable.ad,
    "Angola" to R.drawable.ao,
    "Anguilla" to R.drawable.ai,
    "Antarctica" to R.drawable.aq,
    "Antigua and Barbuda" to R.drawable.ag,
    "Argentina" to R.drawable.ar,
    "Armenia" to R.drawable.am,
    "Aruba" to R.drawable.aw,
    "Australia" to R.drawable.au,
    "Austria" to R.drawable.at,
    "Azerbaijan" to R.drawable.az,
    "Bahamas" to R.drawable.bs,
    "Bahrain" to R.drawable.bh,
    "Bangladesh" to R.drawable.bd,
    "Barbados" to R.drawable.bb,
    "Belarus" to R.drawable.by,
    "Belgium" to R.drawable.be,
    "Belize" to R.drawable.bz,
    "Benin" to R.drawable.bj,
    "Bermuda" to R.drawable.bm,
    "Bhutan" to R.drawable.bt,
    "Bolivia" to R.drawable.bo,
    "Brazil" to R.drawable.br,
    "Cambodia" to R.drawable.kh,
    "Cameroon" to R.drawable.cm,
    "Canada" to R.drawable.ca,
    "Chad" to R.drawable.td,
    "China" to R.drawable.cn,
    "Colombia" to R.drawable.co,
    "Cuba" to R.drawable.cu,
    "Czech Republic" to R.drawable.cz,
    "Denmark" to R.drawable.dk,
    "Djibouti" to R.drawable.dj,
    "Ecuador" to R.drawable.ec,
    "Egypt" to R.drawable.eg,
    "El Salvador" to R.drawable.sc,
    "Estonia" to R.drawable.ee,
    "Finland" to R.drawable.fi,
    "France" to R.drawable.fr,
    "Georgia" to R.drawable.ge,
    "Germany" to R.drawable.de,
    "Greece" to R.drawable.gr,
    "Greenland" to R.drawable.gl,
    "Haiti" to R.drawable.ht,
    "Hong Kong" to R.drawable.hk,
    "Iceland" to R.drawable.`is`,
    "India" to R.drawable.`in`,
    "Israel" to R.drawable.il,
    "Italy" to R.drawable.it,
    "Jamaica" to R.drawable.jm,
    "Japan" to R.drawable.jp,
    "Kuwait" to R.drawable.kw,
    "Liechtenstein" to R.drawable.li,
    "Lithuania" to R.drawable.lt,
    "Madagascar" to R.drawable.mg,
    "Mexico" to R.drawable.mx,
    "Monaco" to R.drawable.mc,
    "Morocco" to R.drawable.ma,
    "New Zealand" to R.drawable.nz,
    "Niger" to R.drawable.ne,
    "Nigeria" to R.drawable.ng,
    "North Korea" to R.drawable.kp,
    "Norway" to R.drawable.no,
    "Pakistan" to R.drawable.pk,
    "Poland" to R.drawable.pl,
    "Qatar" to R.drawable.qa,
    "Romania" to R.drawable.ro,
    "Russia" to R.drawable.ru,
    "Serbia" to R.drawable.rs,
    "Singapore" to R.drawable.sg,
    "Somalia" to R.drawable.so,
    "South Korea" to R.drawable.kr,
    "Sudan" to R.drawable.sd,
    "Sweden" to R.drawable.se,
    "Switzerland" to R.drawable.ch,
    "Thailand" to R.drawable.th,
    "Ukraine" to R.drawable.ua,
    "United Kingdom" to R.drawable.gb,
    "United States of America" to R.drawable.us,
    "Vietnam" to R.drawable.vn,
    "Yemen" to R.drawable.ye,
    "Zimbabwe" to R.drawable.zw
)